### ISSUE TITLE
Adapter no longer sends data since this morning

### ISSUE THREAD

**Issue by SunkHD** [fungus75/ioBroker.zoe2#14]
I have the problem that the adapter has not sent any new data from the ZOE to the iobroker since this morning. Error code in the log file:
```
host.raspberrypi | 2021-02-01 18:59:02.338 | error | instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
zoe2.0 | 2021-02-01 18:59:02.304 | error | (5002) Termination forced due to timeout !
host.raspberrypi | 2021-02-01 18:58:00.024 | warn | instance system.adapter.zoe2.0 already running with pid 5002
```
Falls deutsch möglich ist, wäre mir das lieber:

Also ich habe das Problem das mein Adapter sich seit heute früh nicht mehr aktualisiert. Die Renault App funktioniert. Hab den Neusten Zoe Baujahr 10/2020. 

Mit freundlichen Grüßen
Max Franiel

**Comment by fungus75** [comment]
Hi Max,
sieht so aus als ob die API von Renault geändert wurde: https://github.com/jamesremuscat/pyze/issues/94
Diese Adapter ist natürlich nicht offiziell von Renault zertifiziert, verwende das was pyze bzw. die Folgeprojekte anbieten. Die haben auch mehr Ressourcen, ich selbst bin eine Einmann-Show. Muss also leider abwarten, ob und was pyze da herausfindet. Sorry.

Sobald es dort mehr gibt, wird natürlich gleich angepasst, damit der Adapter wieder richtig funktioniert.

**Comment by SunkHD** [comment]
Hey fungus75,
Vielen dank erstmal für die schnelle Antwort.
Kein Problem finde es gut das sich jemand darum kümmert. Und das es diesen Adapter überhaupt gibt ist toll. Denn die Renault App ist nun wirklich nicht zumutbar xD. Sagt Bescheid wenn man euch irgendwie unterstützen kann.

grüße
Max

**Comment by fprobst170** [comment]
Hallo fungus75,
ich hab zum Testen bei mir den derzeit bekannten Kamareon-Api-Key "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2" fix eingetragen.

Änderungen an er Datei main.js (Zeile 110)

-   Zeile 110			var kamereonapikey  = data.servers.wiredProd.apikey;
+  Zeile 110			var kamereonapikey  = "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2";

Bei mir funktioniert seitem wieder der Adapter.
Vielleicht machst du ein kleines Update - ich denke es würden sich viele freuen.

Mit freundlichen Grüßen
Florian

**Comment by fprobst170** [comment]
Hallo fungus75,
ich hab zum Testen bei mir den derzeit bekannten Kamareon-Api-Key "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2" fix eingetragen.

Änderungen an er Datei main.js-  Zeile 110
`var kamereonapikey  = "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2";`

Bei mir funktioniert seitem wieder der Adapter.
Vielleicht machst du ein kleines Update - ich denke es würden sich viele freuen.

Mit freundlichen Grüßen
Florian

**Comment by epenet** [comment]
Ref https://github.com/hacf-fr/renault-api/issues/181

**Comment by SunkHD** [comment]
wo findet man die main,js datei? oder muss ich den adapter mit der geänderten Datei neu installieren?

**Comment by fprobst170** [comment]
Hallo SunkHD,
die Datei findest du in folgendem Verzeichnis:
/opt/iobroker/node_modules/iobroker.zoe

Nach dem Ändern den Adapter einfach neu starten.

**Comment by SunkHD** [comment]
Vielen dank das hat geklappt. Der Adapter läuft wieder.
ein kleines Update für alle wäre Hilfreich damit er erstmal wieder funktioniert

**Comment by fprobst170** [comment]
Hallo SunkHD,
Gerne. Ich hab nur die Infos die ich auf github gefunden habe für diesen Adapter verwendet.
Von wem der Api-Key nun wirklich ist kann ich nicht sagen da er auf sehr vielen Repositorys zu finden ist.
Kann auch nur Danke sagen. An Fungus75 und den Entdecker des Kamereon-api-key.

**Comment by SunkHD** [comment]
Hey pfrobst170,
danke sag ich auch Aufjedenfall. Hast du eig. mal die Klimatisierung ausprobiert? Scheint bei mir nicht zu funktionieren. 
`
zoe2.0 | 2021-02-02 18:54:35.575 | error | (8588) No valid response from getHVACStatus service
`

**Comment by SunkHD** [comment]
starten tut sie auch nicht

**Comment by fungus75** [comment]
Ich hab die zwischenversion ins GIT hochgeladen. Einfach im ioBroker unter Adapter -> von eigener URL -> Beliebig und dann https://github.com/fungus75/ioBroker.zoe2/tarball/master/ eingeben, dann macht er einen Update. Sollte wieder gehen.

**Comment by fungus75** [comment]
> Hey pfrobst170,
> danke sag ich auch Aufjedenfall. Hast du eig. mal die Klimatisierung ausprobiert? Scheint bei mir nicht zu funktionieren.
> `zoe2.0 | 2021-02-02 18:54:35.575 | error | (8588) No valid response from getHVACStatus service`

Die Klima-Steuerung geht bei einigen ZOEs nicht. Versuch mal, ob es über die APP geht. Bei meinem (1. Generation) geht es, bei anderen wieder nicht. Die ist sehr buggy, liegt aber leider an Renault.

**Comment by fungus75** [comment]
I've upgraded to a working "in between" version. Please go to iobroker => adapter => from own URL => user defined and enter https://github.com/fungus75/ioBroker.zoe2/tarball/master/  => this should upgrade your iobroker-zoe2-Adapter to a working version.

**Comment by fungus75** [comment]
> > Hey pfrobst170,
> > danke sag ich auch Aufjedenfall. Hast du eig. mal die Klimatisierung ausprobiert? Scheint bei mir nicht zu funktionieren.
> > `zoe2.0 | 2021-02-02 18:54:35.575 | error | (8588) No valid response from getHVACStatus service`
> 
> Die Klima-Steuerung geht bei einigen ZOEs nicht. Versuch mal, ob es über die APP geht. Bei meinem (1. Generation) geht es, bei anderen wieder nicht. Die ist sehr buggy, liegt aber leider an Renault.

Hier haben wir uns mal über die HVAC-API unterhalten: https://github.com/fungus75/ioBroker.zoe2/issues/10

**Comment by SunkHD** [comment]
okay danke. Bei mir ging der Klimatisierung vor der api Änderung immer verlässig (außer bei einer Akkukapatität unter ca > 18% xD) Ich schau einfach mal morgen früh ob die Klimatisierung laut meinen Zeitplan funktioniert, da über die Renault App sich auch nichts tut.

**Comment by SunkHD** [comment]
Es scheint so das zurzeit überhaupt kein ZE Server mehr geht. Meine Daten werden wieder nicht mehr aktualisiert. In der Renault App wird mir nicht mal mehr der Batteriestatus angezeigt.

**Comment by fprobst170** [comment]
Aktuell werden die Daten bei mir aktualisiert. Aber es ist nichts neues das die Dienste von Renault nicht immer funktionieren.

**Comment by fungus75** [comment]
Ja leider ist das öfters der Fall. Für mich sieht es so aus, als ob zwischen 22:00 und 23:00 Uhr öfters "Probleme" existieren. Vielleicht stellen dann die Entwickler von Renault eine neue Version live?
2. Februar 2021 22:55, "SunkHD" <notifications@github.com (mailto:notifications@github.com?to=%22SunkHD%22%20<notifications@github.com>)> schrieb:
	Es scheint so das zurzeit überhaupt kein ZE Server mehr geht. Meine Daten werden wieder nicht mehr aktualisiert. In der Renault App wird mir nicht mal mehr der Batteriestatus angezeigt.

**Comment by fungus75** [comment]
Ok für euch, wenn wir den Issue schließen? 
Fraglich ist, ob Renault hier wieder den API-Key anpasst in naher Zukunft. Dann müssten wir wieder nachschärfen.

Wäre es eine Lösung, den API-Key als Parameter in die Config-Seite mit aufzunehmen? Dann muss man sich ggf. informieren, was der aktuelle API-Key ist (könnte man hier z.B. in einem Forum machen?)

**Comment by Slowdown-de** [comment]
Update aus URL hat funktioniert! Du kannst gerne API Key in die Adapter-Config aufnehmen. Mal sehen wie oft der sich noch verändert. Der API-Key betrifft ja auch die Benutzer von PYZE usw. Danke für die schnelle Reaktion!

**Comment by fprobst170** [comment]
Ist eine gute Idee den Api-Key als Parameter in die Config-Seite aufzunehmen. 👍
Issue kannst du gerne schließen.

**Comment by fungus75** [comment]
Es gibt jetzt eine Zwischenversion im GITHUB wo man den API-Key über die config-Seite einpflegen kann. Falls sich da mal wieder was ändert.
