### ISSUE TITLE
Stoppen der Ladung

### ISSUE THREAD

**Issue by Zengaja** [fungus75/ioBroker.zoe2#15]
Hi,

erstmal vielen Dank das du diese tolle APP gemacht hast. :)

Soweit funktioniert die auch, ich habe nur festgestellt das wenn ich über ioBroker die Ladung bei 80% automatisch stoppen lasse, das dann nach dem stoppen der Lademodus geändert wird von sofortigem Laden auf zeitversetztes Laden und mit als Ladeprogramm 1 00:00 bis 00:15 laden eingesetzt und aktiviert wird.

Ein löschen der Ladeprogramme bringt nichts, nach dem nächsten stoppen der Ladung über die App steht es wieder drin.
Hast du eine Idee woran das liegen könnte?

Zengaja

**Comment by fungus75** [comment]
Vielen Dank. Es freut mich wahnsinnig, dass der Adapter so häufig verwendet wird. Fing es doch damit an, dass ich für meinen ZOE eine kleine Lösung wollte...

Zu der Frage: Leider bietet die API keine "Laden-Unterbrechen" Funktion an. Daher war für mich die einzige Möglichkeit das Laden zu stoppen, auf eine geplante Ladung umzustellen, die so kurz als möglich angesetzt ist und zu einer Zeit gesetzt ist, die hoffentlich nicht stört. Daher kam dieses 00:00 bis 00:15 Uhr.

Mir ist hier leider nichts besseres eingefallen.

Durch das "freigeben der Ladung" wird wieder auf "sofortiges Laden" zurückgestellt und somit beginnt das Laden. Mehr gibt leider die API von Renault nicht her.

**Comment by Zengaja** [comment]
Ja, genau so bastel ich mir auch vieles zurecht, nur das ich vieles nicht veröffentliche weil das so speziell ist für meine Bedürfnisse aber einiges doch, aber für Android.

Zum Thema:
Ich verstehe, Danke für die Erklärung. Hatte jetzt echt angenommen die API biete sowas an.
Kannst du mir die Datei (inkl. Pfad) sagen wo ich das ändern könnte? Bzw in den Optionen einbauen das man selbst das Zeitfenster ändern kann? - falls das natürlich mehr wollen, brauch keine extra Wurst :-D
Dieses Zeitfenster ist für mich extrem ungünstig, da ich Abends lade auf 80% und dann erst am nächsten Morgen das Ladekabel ziehe.

Mit Blick auf einige anderen die vllt über die Solarzelle tagsüber laden und evtl. das Ladekabel drin lassen und Nachts dann den teuren Bio/Atom/Kohle Strom laden auch ungünstig. KA obs da überhaupt welche gibt die so laden, war mir nur gerade als Argument eingefallen ;-)

Zengaja

**Comment by Zengaja** [comment]
Mir fällt gerade ein, könnte man diese Zeiten nicht als Objekte in ioBroker freigeben, so könnte man selbst geplante Ladungen programmieren und selbst die Zeiten zum unterbrechen bestimmen ganz ohne Einbau in den Optionen?

**Comment by fungus75** [comment]
Hi,

gute Idee. Was willst du alles angeben? Startzeitpunkt und Dauer?
Oder genügt die Stunde in der die Unterbrechung deaktiviert wird.

Weiß noch nicht genau, wie ich es nennen soll, so dass es klar ist.
Ich hab mir zuerst gedacht, ich mach einen Eintrag ("Stunde für Laden deaktivieren") und das ist dann die Stunde wo er abschaltet.
Aber so könnte ich es natürlich umstellen auf Lademodus: Sofort/Geplant und dann StartzeitpunktGeplanteLadung und DauerGeplanteLadung oder so (englisch) nennen?

cu
 Fungi
4. Februar 2021 17:46, "Zengaja" <notifications@github.com (mailto:notifications@github.com?to=%22Zengaja%22%20<notifications@github.com>)> schrieb:
	Mir fällt gerade ein, könnte man diese Zeiten nicht als Objekte in ioBroker freigeben, so könnte man selbst geplante Ladungen programmieren und selbst die Zeiten zum unterbrechen bestimmen ganz ohne Einbau in den Optionen?

**Comment by fungus75** [comment]
Habe soeben eine Zwischenversion hochgeladen (noch nicht endgültig getestet), wo du über die config-Seite die Stunde einstellen kannst, in der er auf "Programmierte Ladung" geht, wenn du auf Laden Deaktivieren klickst.

**Comment by fungus75** [comment]
Gib mir doch bescheid, ob das so klappt. Wegen einer "frei konfigurierbaren Version", da muss ich mir noch was sauberes überlegen, daher so ein Workaround.

**Comment by Zengaja** [comment]
> 
> Hi, gute Idee. Was willst du alles angeben? Startzeitpunkt und Dauer? Oder genügt die Stunde in der die Unterbrechung deaktiviert wird. Weiß noch nicht genau, wie ich es nennen soll, so dass es klar ist. Ich hab mir zuerst gedacht, ich mach einen Eintrag ("Stunde für Laden deaktivieren") und das ist dann die Stunde wo er abschaltet. Aber so könnte ich es natürlich umstellen auf Lademodus: Sofort/Geplant und dann StartzeitpunktGeplanteLadung und DauerGeplanteLadung oder so (englisch) nennen? cu Fungi 4. Februar 2021 17:46, "Zengaja" <notifications@github.com (mailto:notifications@github.com?to=%22Zengaja%22%20<notifications@github.com>)> schrieb: Mir fällt gerade ein, könnte man diese Zeiten nicht als Objekte in ioBroker freigeben, so könnte man selbst geplante Ladungen programmieren und selbst die Zeiten zum unterbrechen bestimmen ganz ohne Einbau in den Optionen?

Also mir persönlich würde reichen den Start der Ladung einzustellen. Enden soll er ja in meinem Fall wenn die % erreicht ist bzw wenn voll. Schwierig umzusetzen mit dem Hintergrunf das es keine direkte Unterbrechung gibt.
Ich muss mir das auch noch mal durch den Kopf gehen lassen wie man das lösen könnte. Eventuell mit 2 verschiedenen Zeiten und halt die 2. Zeit aktivieren als Unterbrechungszeit.

Als Ende angeben ich denke mal die Dauer, dann ist es ähnlich wie in der App bzw im Auto.

Wo finde ich denn deine "BETA"?
Kenn mich in GitHub nicht so aus, Hatte Repos früher mit der Konkurenz gemacht :D

Aktuell geht deine 0.1.3 Version bei mir nicht, bevor ich gestern updatete, ging sie wunderbar. Muss mir das ganze nochmal angucken wegen der API-Änderung.

Zengaja

**Comment by fungus75** [comment]
Hi Zengaja,

einfach über Adapter -> von eigener URL -> Beliebig und dann https://github.com/fungus75/ioBroker.zoe2/tarball/master/ (https://github.com/fungus75/ioBroker.zoe2/tarball/master/) eingeben den Update machen.
Falls du das schon gemacht hast, bitte in die Config vom Adapter reingehen und dort irgendwas ändern und dann speichern. Er hat wohl noch nicht alle config-parameter sauber gespeichert.

Danach sollte es gehen.
Bei mir hat es gut ausgesehen.

cu
 Fungus75
4. Februar 2021 22:30, "Zengaja" <notifications@github.com (mailto:notifications@github.com?to=%22Zengaja%22%20<notifications@github.com>)> schrieb:
	Also mir persönlich würde reichen den Start der Ladung einzustellen. Enden soll er ja in meinem Fall wenn die % erreicht ist bzw wenn voll. Schwierig umzusetzen mit dem Hintergrunf das es keine direkte Unterbrechung gibt.
Ich muss mir das auch noch mal durch den Kopf gehen lassen wie man das lösen könnte. Eventuell mit 2 verschiedenen Zeiten und halt die 2. Zeit aktivieren als Unterbrechungszeit. 

	Als Ende angeben ich denke mal die Dauer, dann ist es ähnlich wie in der App bzw im Auto. 

	Wo finde ich denn deine "BETA"?
Kenn mich in GitHub nicht so aus, Hatte Repos früher mit der Konkurenz gemacht :D 

	Aktuell geht deine 0.1.3 Version bei mir nicht, bevor ich gestern updatete, ging sie wunderbar. Muss mir das ganze nochmal angucken wegen der API-Änderung. 

	Zengaja

**Comment by fungus75** [comment]
Klappt es? Habe gerade die V0.1.4 hochgestellt. Ist aber nur "markulatur", da der Code nicht gändert wurrde.
Falls was nicht geht, bitte in den Adapter-Setup-Screen rein, irgendein feld ändern, wieder zurück ändern (damit der SAVE-Knopf kommt) und dann save drücken.

**Comment by Zengaja** [comment]
Hi Fungus75,

nach 2 Fehlversuchen (Error-Code 25) hats jetzt geklappt.
Habe in dem neu eingefügten Feld mal 16 eingegeben.
Aktuell läd die Zoe auf. Mal gucken was passiert. Kann ich dir aber erst morgen berichten.

Zengaja

**Comment by Zengaja** [comment]
Hi Fungus75,

mein Update: :)
Hat perfekt funktioniert!

Als Zeit wurde jetzt auch ans Auto 16:00-16:15 eingetragen.

Hab für meine Bedürfnisse auch schon weitere Ideen sofern die Zeit dann auch als Objekt vorliegt.
So könnte man per Script die Zeit immer so abändern das er nie "geplant" nachlädt.

Bin gespannt auf das nächste Update :)

**Comment by Zengaja** [comment]
Kleiner Nachtrag:
Zeit auf 12 geändert, wurde bisher nicht ans Auto übertragen.
Es fand bisher keine weitere Ladung statt.
Eventuell werden die Werte nur übertragen wenn eine Ladung aktiv ist?

**Comment by fungus75** [comment]
Hi Zengaja,
das hab ich schon bemerkt, dass die Übertragung ans Auto nur zu besonderen Events stattfindet. Meiner (Zoe 1. gen) überträgt nur, wenn es aus Sicht ZOE wichtig ist, d.h. wenn er entweder geladen wird oder man mit ihm fährt, d.h. wenn sich der Batteriestand (in welche Richtung auch immer) ändert.

cu
 Fungi
