### ISSUE TITLE
Neuer API Schlüssel

### ISSUE THREAD

**Issue by Starter4711** [fungus75/ioBroker.zoe2#16]
Renault hat einen neuen Schlüssel ausgegeben? Weiß nicht wie man das besser umschreibt.
Bitte um Update des Adapter.
BG

**Comment by fungus75** [comment]
Hatten wir in einer Zwischenversion schon behoben, siehe https://github.com/fungus75/ioBroker.zoe2/issues/14
Jetzt ist aber die neue Version draußen, wo es offiziell behoben ist.

Bitte den Adapter updaten (geht gleich wie du ihn installiert hast).
Und danach bitte in den Setup-Screen rein, irgendwas ändern, wieder zurück ändern (dadurch kommt der SAVE Button) und dann Save drücken.
