### ISSUE TITLE
Error-Log

### ISSUE THREAD

**Issue by Zengaja** [fungus75/ioBroker.zoe2#17]
Hi, ich muss schon wieder nerven :D

Seit 12 Uhr und 1 Sek geht mein Adapter nicht mehr :(

 `zoe2.0 | 2021-02-08 21:10:06.937 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | -- | --
zoe2.0 | 2021-02-08 21:10:06.937 | error | at endReadableNT (_stream_readable.js:1241:12)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at IncomingMessage.emit (events.js:326:22)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at Object.onceWrapper (events.js:420:28)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at Request.emit (events.js:314:20)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at Request.emit (events.js:314:20)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
zoe2.0 | 2021-02-08 21:10:06.937 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.zoe2/main.js:253:44)
zoe2.0 | 2021-02-08 21:10:06.937 | error | (25264) TypeError: Cannot read property 'personId' of undefined
zoe2.0 | 2021-02-08 21:10:06.935 | error | (25264) uncaught exception: Cannot read property 'personId' of undefined`

Als ich zur Arbeit gefahren bin früh ging er noch, also hab nichts verstellt damit sagen will ;)

Zengaja

**Comment by Zengaja** [comment]
vielleicht noch wichtig, davor kommt noch folgender Text:

`2021-02-08 21:20:06.515 - info: zoe2.0 (31825) getgetAccountInfo:{"callId":"6c[....]","errorCode":403007,"errorDetails":"Invalid namespace 'accounts' or method 'getAccountInfo' or you do not have the required permissions to call it. ","errorMessage":"Permission denied","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2021-02-08T20:10:06.489Z"}`

**Comment by fungus75** [comment]
Hi Zengaja, 
selbes Verhalten auch bei mir.

Hab schon die üblichen Verdächtigen geprüft, aber dort gibts noch keine Meldungen dazu:
https://github.com/hacf-fr/renault-api/issues
https://github.com/jamesremuscat/pyze/issues

Muss leider auf die dort vertrösten. Die haben viel tieferen Einblick in die API. Erst wenn dort eine Lösung gefunden ist, kann ich entsprechend nachbauen.

Sorry

**Comment by fungus75** [comment]
Ich glaube, ich habe was gefunden. Habe mir bei https://github.com/hacf-fr/renault-api/issues noch ganz genau angesehen wie der den einen Teil der API (gigya) aufruft und dort haben sich tatsächlich die Parameter-Namen geändert. Das hab ich jetzt bei mir nachgezogen und auf den ersten Blick sieht es gut aus.

Zieh dir bitte die aktualisierte "Zwischenversion" von GitHub. Wenn das bei dir tut, mach ich eine Hauptversion daraus.

**Comment by db-EV** [comment]
Und wenn ihr schon dabei seid, könnt ihr gleich auch noch die gigyaGetAccount-Funktion raus schmeissen.
Die bei getKamereonAccount benötigte personID gibt's schon beim loginToGigya gratis mit dazu.

**Comment by fungus75** [comment]
@db-EV wenn man den Parameter  'include' => 'data', mitgibt. Hab in deinem Code etwas geschmöckert. Danke für den Tipp!

**Comment by SunkHD** [comment]
> Ich glaube, ich habe was gefunden. Habe mir bei https://github.com/hacf-fr/renault-api/issues noch ganz genau angesehen wie der den einen Teil der API (gigya) aufruft und dort haben sich tatsächlich die Parameter-Namen geändert. Das hab ich jetzt bei mir nachgezogen und auf den ersten Blick sieht es gut aus.
> 
> Zieh dir bitte die aktualisierte "Zwischenversion" von GitHub. Wenn das bei dir tut, mach ich eine Hauptversion daraus.

Wie kann ich die Zwischenversion installieren? Hab nochmal den Renault Zoe Adapter von Github gezogen und bei mir funktioniert trotzdem weiterhin der Adapter nicht

**Comment by Zengaja** [comment]
Hi Fungus,

es scheint jetzt wieder zu laufen, im Log sind jetzt auch viel mehr Daten als vorher.
Hab auch extra eine Ladung begonnen und beobachte das ob das alles gut geht.
Ich gebe sobald die Ladung fertig ist (noch 15%) ein Update.

**Comment by Zengaja** [comment]
> 
> 
> > Ich glaube, ich habe was gefunden. Habe mir bei https://github.com/hacf-fr/renault-api/issues noch ganz genau angesehen wie der den einen Teil der API (gigya) aufruft und dort haben sich tatsächlich die Parameter-Namen geändert. Das hab ich jetzt bei mir nachgezogen und auf den ersten Blick sieht es gut aus.
> > Zieh dir bitte die aktualisierte "Zwischenversion" von GitHub. Wenn das bei dir tut, mach ich eine Hauptversion daraus.
> 
> Wie kann ich die Zwischenversion installieren? Hab nochmal den Renault Zoe Adapter von Github gezogen und bei mir funktioniert trotzdem weiterhin der Adapter nicht

einfach https://github.com/fungus75/ioBroker.zoe2/tarball/master/ eintragen und updaten

**Comment by Zengaja** [comment]
@fungus75 Funktioniert! :) Danke für die schnelle Hilfe :)

**Comment by SunkHD** [comment]
> > > Ich glaube, ich habe was gefunden. Habe mir bei https://github.com/hacf-fr/renault-api/issues noch ganz genau angesehen wie der den einen Teil der API (gigya) aufruft und dort haben sich tatsächlich die Parameter-Namen geändert. Das hab ich jetzt bei mir nachgezogen und auf den ersten Blick sieht es gut aus.
> > > Zieh dir bitte die aktualisierte "Zwischenversion" von GitHub. Wenn das bei dir tut, mach ich eine Hauptversion daraus.
> > 
> > 
> > Wie kann ich die Zwischenversion installieren? Hab nochmal den Renault Zoe Adapter von Github gezogen und bei mir funktioniert trotzdem weiterhin der Adapter nicht
> 
> einfach https://github.com/fungus75/ioBroker.zoe2/tarball/master/ eintragen und updaten

genau das hatte ich getan. Funktioniert bei mir leider nicht

**Comment by Zengaja** [comment]
> zoe2.0 	2021-02-09 20:50:03.015 	info 	(1374) kamereonapikey:undefined

bei dir fehlt der kamereonapikey.

geh mal in Instanz und dann in die Einstellungen vom Zoe2.0 und da trag mal den kamereonapikey Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2 ein, dann solte es gehen. Scheint das das feld bei dir frei ist

**Comment by fungus75** [comment]
Falls doch was drinnen steht, irgendwo was ändern (z.B. bei Länderversion), damit der Save-Knopf erscheint. Dort dann auf "SAVE" klicken, damit die geänderten Parameter auch übernommen werden.

**Comment by fungus75** [comment]
Ich schließe die Issue, da es mittlerweile behoben ist/sein sollte.
