### ISSUE TITLE
erneut API Code Änderung durch Renault

### ISSUE THREAD

**Issue by Starter4711** [fungus75/ioBroker.zoe2#18]
Bitte wieder updaten, danke. Oder wie kann ich den Code bekommen?

**Comment by Zengaja** [comment]
Hi,
hast du schon die 0.1.5 Version? Der Key wurde letzte Woche geändert, den hat Fungus schon eingetragen :)

**Comment by fungus75** [comment]
Ich schließe es, da ich glaube, es ist kein echter Fehler.
