### ISSUE TITLE
Terminated: without reason

### ISSUE THREAD

**Issue by Starter4711** [fungus75/ioBroker.zoe2#19]
Hi,
gerade neu den Zoe2 Adapter installiert, bei der 1. Abfrage zeigt er sehr viele Warning.
Bei der 2. Abfrage holt er bereits Daten ab, aber dann läuft es in einen Fehler?
Bitte um Korrektur, vielen Dank!

host.ioBrokerPV | 2021-02-18 17:50:18.987 | info | instance system.adapter.zoe2.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
-- | -- | -- | --
zoe2.0 | 2021-02-18 17:50:18.461 | info | (30750) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zoe2.0 | 2021-02-18 17:50:08.446 | debug | (30750) in: checkPreconAndCharge v0.01

**Comment by fungus75** [comment]
instance system.adapter.zoe2.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
This is not a bug, this is a feature.

Ist leider so, diese Fehlermeldung macht iobroker selbst und bedeutet soviel "zoe-adapter ist fertig". Ist also nur eine Info, kein Fehler.

**Comment by Starter4711** [comment]
OK, bisher war das nicht so, erst heute durch die Neuinstallation sehe ich eben diesen Eintrag im Log.
Aber, dann is ja alle gut! Danke.

**Comment by fungus75** [comment]
Ja, der Logeintrag kommt erst, seitdem ich auf den Compact Mode gewechselt hab, wer für eine Aufnahme ins "normale" Repo notwendig ist.

**Comment by Starter4711** [comment]
Alles klar! Wo darf ich denn sonst um ein Feature fragen, hier ist wohl der falsche Ort.

**Comment by fungus75** [comment]
Klar, gern.
Alternativ: das wäre für Features gedacht, scheint aber nicht ganz stabil zu sein: https://feathub.com/fungus75/ioBroker.zoe2

**Comment by Starter4711** [comment]
Super, danke!
Kommt diese Mail an?
BG Richard

**Comment by Starter4711** [comment]
Morgen, hast du den Eintrag auf feathub gesehen? passt das? BG

**Comment by fungus75** [comment]
Perfekt. Dann schließe ich den Incident.
