### ISSUE TITLE
chargingPower will not be reset

### ISSUE THREAD

**Issue by arturwolf** [fungus75/ioBroker.zoe2#2]
After stop/breaking charging,  charginPower object remains at its last value. It should be set to 0.

**Comment by fungus75** [comment]
Please check the currently committed version 0.0.7
This bug should be fixed.

**Comment by Jack-RK-24** [comment]
after updating to 0.0.7 it's now showing 0 (Zoe Ph2)
![Zoe2_0 7 1](https://user-images.githubusercontent.com/63138075/85051646-0e394100-b198-11ea-8016-e8375042187e.PNG)

**Comment by fungus75** [comment]
Just pushed version 0.0.8. 
@arturwolf if you tell me what ZOE you have, I would add you to the readme to honour your testing?

**Comment by Jack-RK-24** [comment]
v.0.0.8 working well with both values set to 0 after charge done (Zoe Ph2):
![Zoe2_0 0 8](https://user-images.githubusercontent.com/63138075/85106546-a96bfe00-b20c-11ea-99ad-196ca3a8d1ce.PNG)

**Comment by arturwolf** [comment]
> 
> 
> Just pushed version 0.0.8.
> @arturwolf if you tell me what ZOE you have, I would add you to the readme to honour your testing?

Thank you, works as expected. Tested with my R90.
