### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by Starter4711** [fungus75/ioBroker.zoe2#21]
Hallo,
wäre es möglich den Adapter auch ohne Crontab (10min) zu bekommen?
Ich möchte das Updateintervall während der Ladung erhöhen und sonst reduzieren (per Script).
Leider kann ich den Crontab der Instanz nicht löschen? ist dieser Cronjob fest hinterlegt?
Danke!

**Comment by fungus75** [comment]
Neues Feature, wurde hier bereits erfasst:
https://feathub.com/fungus75/ioBroker.zoe2

Aktuell leider sehr wenig freie Ressourcen, wird also etwas dauern, bis ich neue Features in den Adapter aufnehmen werde. Sorry.
