### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by JHA-2021** [fungus75/ioBroker.zoe2#24]
Hi,
I tried to install your adapter as described in my PI4B with raspbian, ioBroker, piVCCU3, influxdb and Grafana but it won't work.
First I tried to install it via ioBroker (Install from own source..) but it wouldn't work, then I tried to install via ssh and received the following message:

![ZOE Adapter](https://user-images.githubusercontent.com/80697380/114204721-cfa88900-9959-11eb-8ffa-48b3e362980c.jpg)

The Adapter doesn`t show on the Adapter list in ioBroker.

**Comment by fungus75** [comment]
Hi JHA-2021,
from me it looks like you installed ioBroker.zoe2 for the user "pi". => this is what your screenshot says,
but ioBroker itself runs under a different user-account.

Please try the following:

Run this command under ssh:

ps -ef|grep -i iobroker

this should show up under which user-account (first column) the iobroker-service is running. Hope it works.

Otherwhise, please just do
ps -ef

and copy the whole output here.

**Comment by JHA-2021** [comment]
Hi DerPilz,

 

thank you for the swift reply. Before you replied I read that I can use a different link (without /tarball/master) to install the adapter directly via ioBroker and succesfully did.

 

Just for the sake of clearing this issue a screenshot as requested.

 



 

Thank you for the great work!

 

Von: DerPilz ***@***.***> 
Gesendet: Freitag, 9. April 2021 20:37
An: fungus75/ioBroker.zoe2 ***@***.***>
Cc: JHA-2021 ***@***.***>; Author ***@***.***>
Betreff: Re: [fungus75/ioBroker.zoe2] Installation Problems (#24)

 

Hi JHA-2021,
from me it looks like you installed ioBroker.zoe2 for the user "pi". => this is what your screenshot says,
but ioBroker itself runs under a different user-account.

Please try the following:

Run this command under ssh:

ps -ef|grep -i iobroker

this should show up under which user-account (first column) the iobroker-service is running. Hope it works.

Otherwhise, please just do
ps -ef

and copy the whole output here.

**Comment by fungus75** [comment]
Thanks for your answe. Then I mark this issue as solved.
