### ISSUE TITLE
issue starting the adapter

### ISSUE THREAD

**Issue by mat9922** [fungus75/ioBroker.zoe2#29]
I get the message

  | error | startInstance system.adapter.zoe2.0: required adapter "adapter-core" not found!

when starting the adapter. 

Any suggestions to that?

**Comment by fungus75** [comment]
Hi @mat9922 
please try to download the newest version from gitlab (just re-install from gitlab as you have done before).
Hope this fix worked!

**Comment by mat9922** [comment]
works like charme now. thank you very much!
