### ISSUE TITLE
Sometime error 1 sometime getHVACstatus error

### ISSUE THREAD

**Issue by Jautze82** [fungus75/ioBroker.zoe2#4]
Halo,

Wenn ich die API Errors ignorieren anschalte bekomme ich:

zoe2.0 | 2020-06-19 07:40:09.077 | info | (5627)   response:{"statusCode":502,"body":"{\"type\":\"TECHNICAL\",\"messages\":[{\"code\":\"err.tech.502\",\"message\":\"{\\\"errors\\\":[{\\\"status\\\":\\\"502\\\",\\\"code\\\":\\\"gateway.processin
-- | -- | -- | --
zoe2.0 | 2020-06-19 07:40:09.077 | info | (5627) error:null
zoe2.0 | 2020-06-19 07:40:09.076 | error | (5627) No valid response from getHVACStatus service

und manchmal bekomme ich ega ob API Errors ignorieren an oder aus ist bekomme ich zwischendrin immer mal wieder:

host.IOBroker | 2020-06-19 08:03:01.248 | error | instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --

ohne vorherige Warnung und ohne das vorher Daten abgerufen werden. Also einfach mittendrin.

Ich habe das gestern mit der Version 0.0.6 und heute mit der 0.0.8 gesehen.

Danke und viele Grüße
Marcel Jaud

**Comment by Jack-RK-24** [comment]
Hallo Jautze, den Fehler beim abrufen des HVAC-Status (Zoe Ph2) habe ich auch kommt aber (zumindest bei mir) von Renault-Seite. Am besten nachvollziehbar wenn Vorklimatisierung bzw. Klimaprogrammierung über die offizielle App schon nicht bzw. nur sporadisch funktionieren. Der Part ist einfach buggy aber angeblich soll ja demnächst (was auch immer das im Zuge der angespannten Finanzsituation bei Renault heißen mag) ein neues Update alles besser machen.
Den 2ten Fehler hatte ich nur, als API Error ignorieren noch nicht vorhanden war, seit dem hab ich das dauerhaft auf on und damit bleibt das script auch nicht mehr hängen bis er terminiert wird. Bei der Zuverlässigkeit der Renault Systeme (gestern z.b. fast den gesamten Nachmittag offline) ist das setting eigentlich ein Muss...  ;)

**Comment by Jautze82** [comment]
Also bei mir ist es trotz API Error ignorieren.


host.IOBroker | 2020-06-19 09:28:00.968 | error | instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
zoe2.0 | 2020-06-19 09:28:00.957 | error | (11099) Termination forced due to timeout !

**Comment by Jack-RK-24** [comment]
Schräg, wie häufig läuft bei Dir das script? Hab’s auf alle 10 Minuten, das reicht idR.

**Comment by Jautze82** [comment]
Alle 5. Kann es aber mal auf alle 10 Minuten stellen ob es dann besser ist.

**Comment by fungus75** [comment]
Sehr interessant. In welchem Schritt bricht es ab? Es werden ja immer die selben Schritte durchlaufen. Vielleicht kann man da was genaues herauslesen (die Schritte erkennt man z.B. anhand der URL-Einträge, also getCockpitURL,...).

Die ursprüngliche Version des Adapters brach ab, sobald von einem API-Aufruf eine Fehlermeldung zurück kam. Leider kommen von einigen API-Aufrufen immer wieder Fehler zurück. Man erkennt es auch in der App, die liefert auch öfters "Müll" bzw. gar nichts. Ich dachte zuerst, es ist immer um 22:00 Uhr herum, scheint aber auch zu anderen Zeiten aufzutreten. Vielleicht wird dann auch was auf deren Seite umgestellt? Weiß ich leider nicht.

**Comment by Jautze82** [comment]
host.IOBroker	2020-06-20 13:33:01.184	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 13:23:01.075	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 13:13:01.217	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 13:03:01.282	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 12:53:01.102	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 12:43:01.318	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 12:33:00.899	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 12:23:01.077	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 12:13:01.077	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 12:03:01.309	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 11:53:01.179	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 11:43:01.235	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 11:33:01.194	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 11:23:01.154	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 11:13:01.102	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 11:03:01.339	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 10:53:01.031	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 10:43:01.001	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 10:33:01.240	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 10:23:01.038	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker	2020-06-20 10:13:01.068	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

Das ist von heute morgen.

Ein typischer Ablauf sieht so aus:
host.IOBroker	2020-06-20 12:03:01.309	error	instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
zoe2.0	2020-06-20 12:00:08.517	info	(7258) getLocation:{"data":{"type":"Car","id":"FIN","attributes":{"gpsLatitude":Koordinaten,"gpsLongitude":Koordinaten,"lastUpdateTime":"2020-06-19T16:33:37Z"}}}
zoe2.0	2020-06-20 12:00:06.960	info	(7258) getLocation-url:https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/1a6d1d6b-27e6-466b-8b34-40d91f526bb9/kamereon/kca/car-adapter/v1/cars/FIN/location?country=DE
zoe2.0	2020-06-20 12:00:06.959	info	(7258) getCockpit:{"data":{"type":"Car","id":"FIN","attributes":{"fuelAutonomy":0,"fuelQuantity":0,"totalMileage":412.15}}}
zoe2.0	2020-06-20 12:00:06.076	info	(7258) getCockpit-url:https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/1a6d1d6b-27e6-466b-8b34-40d91f526bb9/kamereon/kca/car-adapter/v2/cars/FIN/cockpit?country=DE
zoe2.0	2020-06-20 12:00:06.072	info	(7258) getBatteryStatus:{"data":{"type":"Car","id":"FIN","attributes":{"timestamp":"2020-06-20T09:20:06Z","batteryLevel":99,"batteryTemperature":20,"batteryAutonomy":369,"batteryCapacity
zoe2.0	2020-06-20 12:00:05.004	info	(7258) getBatteryStatus-url:https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/1a6d1d6b-27e6-466b-8b34-40d91f526bb9/kamereon/kca/car-adapter/v2/cars/FIN/battery-status?countr
zoe2.0	2020-06-20 12:00:05.004	info	(7258) getKamereonCars:{"accountId":"1a6d1d6b-27e6-466b-8b34-40d91f526bb9","country":"DE","vehicleLinks":[{"brand":"RENAULT","vin":"FIN","status":"ACTIVE","linkType":"USER","garageBrand"
zoe2.0	2020-06-20 12:00:04.111	info	(7258) kamereonaccesstoken:eyJ0eXAiOiJKV1QiLCJ6aXAiOiJOT05FIiwia2lkIjoiVjRTSkxzK3ZUZ0NRSS9IYmxVbjh5WkFDZzJrPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJHSUdZQVdJUkVELWNmNGEwOWExLTRhNTAtNGJlOS1iNTgwLWRiMWZjYzliN
zoe2.0	2020-06-20 12:00:04.111	info	(7258) getKamereonAccessToken:{"nonce":"f4333231-3afd-4862-89a0-01c026c65313","scope":"openid profile vehicles","accessToken":"eyJ0eXAiOiJKV1QiLCJ6aXAiOiJOT05FIiwia2lkIjoiVjRTSkxzK3ZUZ0NRSS9IYmxVbjh5W
host.IOBroker	2020-06-20 12:00:04.057	info	instance system.adapter.solaredge.0 started with pid 7332
zoe2.0	2020-06-20 12:00:03.014	info	(7258) kamereonaccountid:1a6d1d6b-27e6-466b-8b34-40d91f526bb9
zoe2.0	2020-06-20 12:00:03.014	info	(7258) accounts:[{"accountId":"1a6d1d6b-27e6-466b-8b34-40d91f526bb9","accountType":"MYRENAULT","accountStatus":"ACTIVE","country":"DE","personId":"cf4a09a1-4a50-4be9-b580-db1fcc9b70df","relationType":
zoe2.0	2020-06-20 12:00:03.013	info	(7258) getKamereonAccount:{"personId":"cf4a09a1-4a50-4be9-b580-db1fcc9b70df","type":"I","country":"DE","firstName":"Name","lastName":"Jaud","idp":{"idpId":"939e5878586d4bf2a655b513e0f45c3f","idpType
zoe2.0	2020-06-20 12:00:02.679	info	(7258) kamereonpersonid:cf4a09a1-4a50-4be9-b580-db1fcc9b70df
zoe2.0	2020-06-20 12:00:02.679	info	(7258) getgetAccountInfo:{"callId":"d266800af95b4d1baddc11fc9fc0b8ad","errorCode":0,"apiVersion":2,"statusCode":200,"statusReason":"OK","time":"2020-06-20T10:00:02.654Z","registeredTimestamp":15911916
zoe2.0	2020-06-20 12:00:02.387	info	(7258) gigya_jwttoken:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyIsImtleWlkIjoiUkVRME1VUTVOME5DUlRKRU16azNNMFUxUmtORFEwVTBRME
zoe2.0	2020-06-20 12:00:02.387	info	(7258) getJWTFullbody:{"callId":"b4f1a5e83747416da7ee77cab6e1e4f2","errorCode":0,"apiVersion":2,"statusCode":200,"statusReason":"OK","time":"2020-06-20T10:00:02.271Z","ignoredFields":"","id_token":"ey
zoe2.0	2020-06-20 12:00:02.111	info	(7258) sessionInfo:{"cookieName":"gac_3_7PLksOyBRkHv126x5WhHb-5pqC1qFR8pQjxSeLB6nhAnPERTUlwnYoznHSxwX668","cookieValue":"st2.s.AcbHA-b0SA.GI4v_tihV6sCy86jIlMoXGTPX-5zeQRW5YQOiOInuwMHWXXZ_Rro6zw8gyztdM
zoe2.0	2020-06-20 12:00:02.110	info	(7258) FullBody:{"callId":"8f79a19a475849b0956fc601757d1b87","errorCode":0,"apiVersion":2,"statusCode":200,"statusReason":"OK","time":"2020-06-20T10:00:02.074Z","registeredTimestamp":1591191663,"UID":
zoe2.0	2020-06-20 12:00:01.775	info	(7258) kamereonapikey:oF09WnKqvBDcrQzcW1rJNpjIuy7KdGaB
zoe2.0	2020-06-20 12:00:01.774	info	(7258) kamereonrooturl:https://api-wired-prod-1-euw1.wrd-aws.com
zoe2.0	2020-06-20 12:00:01.774	info	(7258) gigyaapikey:3_7PLksOyBRkHv126x5WhHb-5pqC1qFR8pQjxSeLB6nhAnPERTUlwnYoznHSxwX668
zoe2.0	2020-06-20 12:00:01.774	info	(7258) gigyarooturl:https://accounts.eu1.gigya.com
zoe2.0	2020-06-20 12:00:01.295	info	(7258) URL: https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_de_DE.json
zoe2.0	2020-06-20 12:00:01.295	info	(7258) ignoreApiError:true
zoe2.0	2020-06-20 12:00:01.295	info	(7258) Country:DE
zoe2.0	2020-06-20 12:00:01.294	info	(7258) VIN:FIN
zoe2.0	2020-06-20 12:00:01.294	info	(7258) Locale:de_DE
zoe2.0	2020-06-20 12:00:01.294	info	(7258) Username:Name@Name.de
zoe2.0	2020-06-20 12:00:01.276	info	(7258) starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.zoe2, node: v12.18.1, js-controller: 3.1.6

Viele Grüße
Marcel

**Comment by fungus75** [comment]
Ich habe gerade eine Zwischenversion auf github gestellt, die einfach noch zusätzlich die GPS-Koordinaten rausloggt. Es sieht so aus, als ob er genau da abbricht und ich hätte gern das als weitere Information.

Leider hab ich einen Zoe 1. Generation, die haben noch keine GPS-Unterstützung.

Bitte updaten und dann den Logauszug schicken. Es genügen die letzten 5 bis 10 Zeilen.

Bitte immer Cookies und Tokens aus dem Output ebenfalls löschen. Also alles was so ewiglange Buchstaben-Zahlen-Kombinationen darstellt.

**Comment by Jautze82** [comment]
Hallo,

also im Moment läuft es so wie es soll.

Ich habe nur immer:


zoe2.0 | 2020-06-25 13:05:07.401 | info | (29498)   response:{"statusCode":502,"body":"{\"type\":\"TECHNICAL\",\"messages\":[{\"code\":\"err.tech.502\",\"message\":\"{\\\"errors\\\":[{\\\"status\\\":\\\"502\\\",\\\"code\\\":\\\"gateway.processi
-- | -- | -- | --
zoe2.0 | 2020-06-25 13:05:07.401 | info | (29498) error:null
zoe2.0 | 2020-06-25 13:05:07.400 | error | (29498) No valid response from getHVACStatus service
zoe2.0 | 2020-06-25 13:05:06.723 | info | (29498)   getHVACStatus-url:https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/[buchstaben-Zahlen]kamereon/kca/car-adapter/v1/cars/[VIN]/hvac-status?country=D

**Comment by fungus75** [comment]
Hi Marcel,
ja, das ist leider so. Die API von Renault ist nicht sehr stabil. Es gibt immer wieder Unterbrüche, Minuten später klappt es wieder. Schade. Aber in Summe geht es. Schließe daher das Ticket
