### ISSUE TITLE
Adapter throws errors in the log

### ISSUE THREAD

**Issue by MichaelSchaaf999** [fungus75/ioBroker.zoe2#41]
ZOE2-Adapter throws errors:

2022-03-16 12:00:06.572 | error | instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | --
zoe2.0 | 2022-03-16 12:00:06.061 | error | Cannot read property 'status' of undefined
zoe2.0 | 2022-03-16 12:00:06.061 | error | TypeError: Cannot read property 'status' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:344:29 at processTicksAndRejections (internal/process/task_queues.js:95:5)
zoe2.0 | 2022-03-16 12:00:06.061 | error | unhandled promise rejection: Cannot read property 'status' of undefined
zoe2.0 | 2022-03-16 12:00:06.061 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zoe2.0 | 2022-03-16 12:00:06.060 | warn | Terminated (JS_CONTROLLER_STOPPED): Without reason
zoe2.0 | 2022-03-16 12:00:06.060 | error | Error in step 5, errorCode: 2
zoe2.0 | 2022-03-16 12:00:06.060 | error | Error: Request failed with status code 403
zoe2.0 | 2022-03-16 12:00:06.059 | error | No valid response1 from getKamereonAccount service

What are we expected to do with this?

Best regards
Michael

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/53481090/158577228-d9a72fb0-8357-4b2d-9598-23b976772cd6.png">

**Comment by fungus75** [comment]
Same issue as here https://github.com/jamesremuscat/pyze/issues/94
looks like Renault changed something within the api.

**Comment by fungus75** [comment]
Please go to adapter settings and use VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss as kameron API Key

**Comment by fungus75** [comment]
Here the new APi Key is also shown: https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7?permalink_comment_id=4100324#gistcomment-4100324

**Comment by MichaelSchaaf999** [comment]
New kamereon API key Inserted. Adapter restarted.
Watching the behaviour of the adapter now.
Thx.

**Comment by MichaelSchaaf999** [comment]
Actual data now in the ZOE adapter datapoints.
Seems to work fine now.
Thank you! Fast response!
