### ISSUE TITLE
No valid response from getKamereonAccount service

### ISSUE THREAD

**Issue by Coalado** [fungus75/ioBroker.zoe2#42]
Seit einigen Tagen habe ich nur noch diesen Fehler:
`

zoe2.0 | 2022-03-24 20:37:53.416 | warn | Terminated (JS_CONTROLLER_STOPPED): Without reason
-- | -- | -- | --
zoe2.0 | 2022-03-24 20:37:53.416 | error | Error in step 5, errorCode: 2
zoe2.0 | 2022-03-24 20:37:53.416 | debug | in: processingFailed, curStep: 5
zoe2.0 | 2022-03-24 20:37:53.415 | error | No valid response from getKamereonAccount service
`

**Comment by fungus75** [comment]
Hi,

ist genau der Fehler: https://github.com/fungus75/ioBroker.zoe2/issues/41
Renault hat den API-Key geändert.

Ich werde die Fehlermeldung verbesssern, dass man in Zukunft gleich auf ein mögliches API-Key-Problem hingewiesen wird.

**Comment by fungus75** [comment]
Ich habe gerade eine zwischenversion auf Github gestellt (einfach über den Adapter => Erweitert => Externe Quelle => Sonstige URL "drüber" installieren) die hier eine bessere Fehlermeldung ausgibt und auf https://github.com/fungus75/ioBroker.zoe2/wiki verweist.

Damit sollte die Fehlersuche einfacher sein.
