### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Zengaja** [fungus75/ioBroker.zoe2#43]
Hi,

seit heute 16:40 bekomme ich folgende Fehlermeldung;

`<html><body>

host.ioBroker | 2022-05-17 19:30:11.538 | error | instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
zoe2.0 | 2022-05-17 19:30:11.016 | error | Cannot read property 'status' of undefined
zoe2.0 | 2022-05-17 19:30:11.015 | error | TypeError:  Cannot read property 'status' of undefined    at  /opt/iobroker/node_modules/iobroker.zoe2/main.js:101:29    at  processTicksAndRejections (internal/process/task_queues.js:95:5)
zoe2.0 | 2022-05-17 19:30:11.014 | error | unhandled promise rejection: Cannot read property 'status' of undefined
zoe2.0 | 2022-05-17 19:30:11.013 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
zoe2.0 | 2022-05-17 19:30:11.011 | warn | Terminated (JS_CONTROLLER_STOPPED): Without reason
zoe2.0 | 2022-05-17 19:30:11.010 | error | Error in step 0, errorCode: 2
zoe2.0 | 2022-05-17 19:30:11.009 | error | Error: Request failed with status code 403
zoe2.0 | 2022-05-17 19:30:11.008 | error | No valid response1 from Renault server

</body>
</html>`

Hast du eine Idee woran es liegen könnte?

**Comment by fungus75** [comment]
Hi,

Renault hat wieder was an der API umgestellt. Ich teste gerade einen Workaround.

**Comment by fungus75** [comment]
Hol dir bitte den aktuellen Stand vom GIT-Server. Damit sollte der Adapter-Aufruf wieder klappen.

**Comment by Dreistein19** [comment]
Danke für dein Mühe.
