### ISSUE TITLE
App throws errors: Log

### ISSUE THREAD

**Issue by MichaelSchaaf999** [fungus75/ioBroker.zoe2#44]
2022-05-18 09:00:04.734 | error | Cannot read property 'status' of undefined
-- | -- | --
zoe2.0 | 2022-05-18 09:00:04.733 | error | TypeError: Cannot read property 'status' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:101:29 at processTicksAndRejections (internal/process/task_queues.js:95:5)
zoe2.0 | 2022-05-18 09:00:04.733 | error | unhandled promise rejection: Cannot read property 'status' of undefined
zoe2.0 | 2022-05-18 09:00:04.733 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zoe2.0 | 2022-05-18 09:00:04.733 | warn | Terminated (JS_CONTROLLER_STOPPED): Without reason
zoe2.0 | 2022-05-18 09:00:04.732 | error | Error in step 0, errorCode: 2
zoe2.0 | 2022-05-18 09:00:04.732 | error | Error: Request failed with status code 403
zoe2.0 | 2022-05-18 09:00:04.731 | error | No valid response1 from Renault server

<img width="793" alt="image" src="https://user-images.githubusercontent.com/53481090/168978379-309a9ce0-7a00-46ea-a8b6-21aabfbe458e.png">

What can I do?

Best
M

**Comment by fungus75** [comment]
Please upgrade to the most recent version. I've commited a fix yesterday.

**Comment by fungus75** [comment]
Sorry, because it is something in between, the new version still has the same "ID" as before.
Use "install from GIT" and the url https://github.com/fungus75/ioBroker.zoe2.git to get the version from yesterday that should work again.

**Comment by MichaelSchaaf999** [comment]
Done, thanks.
