### ISSUE TITLE
batteryAvailableEnergy wird nicht mehr aktualisiert/passt nicht zum Ladestand

### ISSUE THREAD

**Issue by Wiednitz** [fungus75/ioBroker.zoe2#49]
Hallo,

seit einigen Wochen wird der Wert "batteryAvailableEnergy" nicht mehr aktualisiert bzw. ändert sich nicht bei Ladung.
Zoe wurde grad geladen, zu Beginn 46% mit 19kwh, bei 100% ebenfalls noch 19 kWh.
Ist das nur bei mir so oder kann das jemand bestätigen ???

Danke

**Comment by albundy0815** [comment]
kann ich so bestätigen.

**Comment by Wiednitz** [comment]
Ja ist schon seit Dezember so...

**Comment by fungus75** [comment]
Ich kann natürlich nur das Anzeigen, was mir die API zur Verfügung stellt. Und leider ist die nicht offiziell, d.h. da gibt es zum Glück ein paar Spezialisten, die sich die Arbeit gemacht haben und die Apps reverse-Engineered haben.

Aber gerade ausprobiert: Bei mir kommt ein Wert?

**Comment by Wiednitz** [comment]
Ja war kein Vorwurf an dich, im Dezember war es so, das der Wert nie zum aktuellen Ladestand gepasst hatte. Kann es zur Zeit nicht überprüfen, wie es aktuell ist, Zoe ist schon seit Monaten in der Werkstatt.

**Comment by fungus75** [comment]
Sorry, es sollte auch nicht zu böse rüberkommen. Leider ist die Renault-API sehr instabil. Es gibt Zeiten, da geht sie nicht (bei mir immer so um +/- 20:00 Uhr) oder eben dieses Wochenende ging auch nichts. Aber aktuell liefert er mir wieder sehr gute Werte.

Achtung: der API-Key wurde vor kurzem wieder geändert. Hier ist der aktuelle jeweils abgelegt: https://github.com/fungus75/ioBroker.zoe2/wiki

Bitte prüfen, ob es bei euch wieder soweit klappt.

**Comment by albundy0815** [comment]
den API Key habe ich vor kurzem auch angepasst, sonst wären überhaupt keine Daten mehr reingekommen.
Aktuell sehen die Werte inkl. der BatteryAvailableEnergy valide & aktuell aus. Danke
