### ISSUE TITLE
Kamereon token request fails and stops Adapter / not req‘d anymore

### ISSUE THREAD

**Issue by Jack-RK-24** [fungus75/ioBroker.zoe2#6]
According to similar Issue described here: https://github.com/jamesremuscat/pyze/pull/74

the Kameron token is not req‘d anymore, however when try using it will throw an error and the following requests fail...

**Comment by fungus75** [comment]
Please update to the current version on github.
Yesterday damack issued an update (Pull-Request) that should fix the issue (worked for me).

**Comment by Jack-RK-24** [comment]
Updated and I can confirm, it‘s working again.
