### ISSUE TITLE
Wrong charge power

### ISSUE THREAD

**Issue by Wiednitz** [fungus75/ioBroker.zoe2#9]
AC Power wallbox is 11,7 kw, iobroker shows 25,5 ... 71,6 !?

**Comment by fungus75** [comment]
Can you please post a screenshot (maybe vin invalidated)? And can you please post the part of the logfile with getBatteryStatus (please also invalidate your vin)?

**Comment by Wiednitz** [comment]
`getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-12T15:27:32Z","batteryLevel":36,"batteryTemperature":20,"batteryAutonomy":107,"batteryCapacity":0,"batteryAvailableEnergy":19,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":240,"chargingInstantaneousPower":71.6}}}`

Screenshot at next charge......

**Comment by fungus75** [comment]
As you can see, this 71.6 or 18.1 comes directly from the Renault-Webservice. The strange thing is, that on my ZOE (1st gen), I get the Data back in Watts, so my ZOE shows me something like 7600. And your values are complete strange...

I use the same API as https://github.com/jamesremuscat/pyze so I checked if there is something similar known? Didn't find anything there.

So, I guess it is a problem with the renault-API and therefore not able to be fixed in this adapter. Sorry.

**Comment by Wiednitz** [comment]
Same Problem is here

**Comment by fungus75** [comment]
Thanks for the link. I just looked at the open issues there.
But do these guys have a solution? They are talking about that this value looks like it is double as it should be.

If wanted, I can add a new setup-parameter "chargingPowerDivisor" where you can enter 2 in your case (1 is default) and I will use that parameter to "recalculate" the current/correct charging power. Would this be a solution?

**Comment by Wiednitz** [comment]
Not really. Ac power was always 11,5 kw, but the value vary between 71,6 at beginn and 18 at the end .....

**Comment by fungus75** [comment]
Ok, then I guess the only way is, that you ignore this value?
Of course, I could add a config-parameter "override charging power with", but is that a good solution?

**Comment by Wiednitz** [comment]
I will analyze this value, maybe i find a connection with other values.....

**Comment by Wiednitz** [comment]
full charge log from other Lidl wallbox .... maybe it's amps (Ampere A) ?

`getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T16:40:25Z","batteryLevel":56,"batteryTemperature":20,"batteryAutonomy":179,"batteryCapacity":0,"batteryAvailableEnergy":28,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":170,"chargingInstantaneousPower":22.4}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T16:43:57Z","batteryLevel":58,"batteryTemperature":20,"batteryAutonomy":183,"batteryCapacity":0,"batteryAvailableEnergy":29,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":165,"chargingInstantaneousPower":18.3}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T16:48:57Z","batteryLevel":60,"batteryTemperature":20,"batteryAutonomy":189,"batteryCapacity":0,"batteryAvailableEnergy":30,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":160,"chargingInstantaneousPower":18.1}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T16:53:57Z","batteryLevel":62,"batteryTemperature":20,"batteryAutonomy":196,"batteryCapacity":0,"batteryAvailableEnergy":31,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":150,"chargingInstantaneousPower":18}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T16:59:57Z","batteryLevel":65,"batteryTemperature":20,"batteryAutonomy":204,"batteryCapacity":0,"batteryAvailableEnergy":32,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":140,"chargingInstantaneousPower":18}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:04:34Z","batteryLevel":67,"batteryTemperature":20,"batteryAutonomy":210,"batteryCapacity":0,"batteryAvailableEnergy":33,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":135,"chargingInstantaneousPower":17.8}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:08:43Z","batteryLevel":68,"batteryTemperature":20,"batteryAutonomy":213,"batteryCapacity":0,"batteryAvailableEnergy":34,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":130,"chargingInstantaneousPower":19}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:13:43Z","batteryLevel":70,"batteryTemperature":20,"batteryAutonomy":220,"batteryCapacity":0,"batteryAvailableEnergy":35,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":120,"chargingInstantaneousPower":18.9}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:19:43Z","batteryLevel":73,"batteryTemperature":20,"batteryAutonomy":229,"batteryCapacity":0,"batteryAvailableEnergy":36,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":110,"chargingInstantaneousPower":18.5}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:25:43Z","batteryLevel":75,"batteryTemperature":20,"batteryAutonomy":236,"batteryCapacity":0,"batteryAvailableEnergy":37,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":105,"chargingInstantaneousPower":13.9}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:30:43Z","batteryLevel":77,"batteryTemperature":20,"batteryAutonomy":242,"batteryCapacity":0,"batteryAvailableEnergy":38,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":95,"chargingInstantaneousPower":13.7}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:36:52Z","batteryLevel":80,"batteryTemperature":20,"batteryAutonomy":251,"batteryCapacity":0,"batteryAvailableEnergy":40,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":90,"chargingInstantaneousPower":14.9}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:43:11Z","batteryLevel":82,"batteryTemperature":20,"batteryAutonomy":257,"batteryCapacity":0,"batteryAvailableEnergy":41,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":80,"chargingInstantaneousPower":14.1}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:49:11Z","batteryLevel":84,"batteryTemperature":20,"batteryAutonomy":264,"batteryCapacity":0,"batteryAvailableEnergy":42,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":75,"chargingInstantaneousPower":14}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T17:56:11Z","batteryLevel":87,"batteryTemperature":20,"batteryAutonomy":273,"batteryCapacity":0,"batteryAvailableEnergy":43,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":65,"chargingInstantaneousPower":14}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T18:03:11Z","batteryLevel":90,"batteryTemperature":20,"batteryAutonomy":282,"batteryCapacity":0,"batteryAvailableEnergy":45,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":50,"chargingInstantaneousPower":14.9}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T18:18:11Z","batteryLevel":96,"batteryTemperature":20,"batteryAutonomy":301,"batteryCapacity":0,"batteryAvailableEnergy":48,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":30,"chargingInstantaneousPower":12}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T18:26:45Z","batteryLevel":99,"batteryTemperature":20,"batteryAutonomy":313,"batteryCapacity":0,"batteryAvailableEnergy":49,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":15,"chargingInstantaneousPower":11.2}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T18:33:11Z","batteryLevel":99,"batteryTemperature":20,"batteryAutonomy":318,"batteryCapacity":0,"batteryAvailableEnergy":50,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":15,"chargingInstantaneousPower":7.1}}}

getBatteryStatus:{"data":{"type":"Car","id":"VF1XXXXXXXXXXXXXX","attributes":{"timestamp":"2020-10-15T18:38:11Z","batteryLevel":99,"batteryTemperature":20,"batteryAutonomy":322,"batteryCapacity":0,"batteryAvailableEnergy":51,"plugStatus":1,"chargingStatus":1,"chargingRemainingTime":15,"chargingInstantaneousPower":5.3}}}
`

**Comment by fungus75** [comment]
Yes, that could be. Strange, that it returns on different ZOEs different Units (on mine it is looks like Watts: 7600 and so on).

Now the question is, should we do some calculations? If so, than we probably have to less values to do so: I don't know if you are connected to 3 or to only one phase. Or can you stay with that?

Maybe we also can adjust the documentation?

**Comment by Wiednitz** [comment]
all wallboxes were 3 phases previously....

Kann man hier auch auf Deutsch schreiben ? 🤔

"DerPilz" scheint doch deutschen Ursprungs 🤔

**Comment by fungus75** [comment]
Ich schreibe einfach in der Sprache zurück, in der ich angeschrieben werde.

Ja, das es jetzt immer 3-phasig war, ist nett, aber leider kommt das von der API nicht zurück.
D.h. wenn du jetzt einmal 1-phasig ladest, dann würde die Berechnung nicht mehr stimmen.

Natürlich könnte ich jetzt einen Parameter einbauen (Umrechenfaktor chargingPowerFaktor) den du z.B. auf 3*240 = 720 setzen könntest. Aber der stimmt natürlich nur, wenn du auch wirklich 3-Phasig ladest.

Wäre das eine Lösung?

**Comment by Wiednitz** [comment]
Fein, ich habe in Englisch begonnen, weil GitHub auf Englisch ist. Aber sich in technischen Sachen korrekt auf Englisch auszudrücken, ist auch nicht Jedermanns Fall.

Jetzt verstehe ich auch deinen Einwand mit den Phasen, da hast du wahr.

Bei dem Log was ich gepostet habe, könnte man Ampere für eine Möglichkeit halten. Bei einer anderen Lidl Wallbox begann das Laden aber mit den 71,6 und verringerte sich erst nach 30 Minuten... Passt also auch nicht wirklich mit Ampere. Den Wert muss man vor einer Änderung im Adapter erstmal beobachten. Änderungen kann man erstmal lokal mit Script machen.

Was allerdings toll wäre, den Wert "LastupdateTime" in den Objekten darzustellen. Der Renault Server schickt die Daten ab und zu auch zeitverzögert und mal aktuell. Die Zeitangabe scheint aber Pariser Zeitzone zu sein, aktuell 2h Unterschied.

**Comment by fungus75** [comment]
Hol dir doch bitte die aktuellste Version aus GitHub (einfach wieder über das Icon "installieren aus eigener URL" im Adapter-Tab. Dort gibts neu "batteryTS".

Das chargingInstantaneousPower bei manchen ZOEs auf einen Wert ungleich 0 steht, wenn nicht geladen wird, hatten wir schon mal als Bug und dort habe ich es einfach im Programmcode auf 0 gesetzt (wenn ich erkenne, dass der Zoe nicht geladen wird).

**Comment by Wiednitz** [comment]
herzlichen Dank. Die Buttons für charge sind ja auch neu, oder !? Dachte ich hätte die letzte Version vom Sommer.....

Die Teile um den esp32 CanSee dongle zu bauen müssten heute eintreffen aus China, mal sehen ob das weitere Aufklärung bringt.

**Comment by fungus75** [comment]
Bin gespannt, ob bei dir die Buttons gehen. Bei mir (gen1) gehen sie sehr sehr fragwürdig. Würde sagen 90% der Zeit nicht.

welchen Zoe hast du?

**Comment by Wiednitz** [comment]
ZOE Ph2 von diesem September. 

Die Teile sind nun da, zumindest für das Innenleben des Dongle. Statt dem OBDII Gehäuse wurde irgend ein Stecker geliefert.

Ich nutze ja die EVSE-WB mit EVSE Wifi, so kann ich den Ladestand gut steuern. Die buttons werde ich bei nächster Gelegenheit testen, um die Ladung nicht durch die EVSE sondern die ZOE zu unterbrechen. Mein Gedanke ist, das die ZOE dann bei der Vorklimatisierung den Strom aus dem Netz nimmt und nicht aus der Batterie !?

**Comment by StrathCole** [comment]
Nur um auch etwas zum ursprünglichen Thema zu sagen: Ich lade aktuell zwischendurch mit einem Schuko-Notladekabel und einer Leistung von ca. 2kW. Die Angabe der Api ist aber dennoch:
`"chargingInstantaneousPower":71.4`

**Comment by StrathCole** [comment]
@fungus75  Ich bin auch der Meinung, dass die Angabe in Ampere angegeben werden könnte. Ich kann aktuell nur mit dem Hausstrom und einem Notladekabel laden, das 10A oder 16A leistet (umschaltbar). Ich habe mir die Ladeleistung bei mir noch einmal genauer angeschaut (Grafana). Scheinbar ist die Angabe meist zwischen 10.5 und 11, nur selten darüber. Als der Wagen fast voll geladen war (99%) ging die Leistung runter auf ~8. Das könnte also durchaus sein.

Bei mir entspräche das bei ~10-11A und 230V einer Wattzahl von ca. 2.400, was auch grob (kann nur den gesamten Hausverbrauch sehen) dem entspricht, was ich an Hausverbrauch minus sonstige Geräte sehe (mit etwa 10% Schwankungen).

**Comment by fungus75** [comment]
Ok, was ist dann die Lösung?
Prinzipiell steht euch natürlich frei, die Werte zu verwenden, wie ihr wollt. D.h. wenn ihr diesen Wert eher als Ampere seht, dann kann man das ja so machen.

Was ich auf meiner Seite anbieten könnte, einen ChargingPowerFactor. Dort kann man dann z.B. 240 oder 400 hinterlegen, und dann macht er quasi daraus Watt. Wie gesagt, ohne Rücksicht darauf, ob er jetzt auch wirklich an einem Stecker mit einer entsprechenden Spannung hängt.

Oder wir lassen es einfach so, wie es aktuell ist.

**Comment by StrathCole** [comment]
> Oder wir lassen es einfach so, wie es aktuell ist.

Von meiner Seite aus ist keine Aktion notwendig. Ich kann den Wert nutzen, wie er ist.
